config/routes.rb
JobSite::Application.routes.draw do

  root 'job_listing#index'

resources :descriptions  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController


def new
end

def create
    render plain: params[:description].inspect
end

end

app/controllers/job_listing_controller.rb
class JobListingController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/job_listing_helper.rb
module JobListingHelper
end

app/views/descriptions/create.html.erb
<p>Your entry has been successfully added.</p>

app/views/descriptions/new.html.erb
<h1>Job Description</h1>
<h2>Please write about what job you do in our little form. We want people less confused about different jobs</h2>

<%= form_for :description, url: descriptions_path do |d| %>
<p>
    <%= d.label :job_title %>
    <%= d.text_field :job_title %>
</p>

<p>
    <%= d.label :job_description %>
    <%= d.text_area :job_description %>
</p>

<p>
    <%= d.submit %>
</p>

<% end %>

app/views/job_listing/index.html.erb
<h1>Jobs</h1>

<h2>Jobs in tech</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>